# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3960626206a25d19c37d34b0b30c3e3a19ebb883bab5f4ba83f6e2a9c7b2f4955cdf339ad8190a084b9926111a99b27062e6670aa4ec83095ae5830cbacebecd

test:
  secret_key_base: e101554889aec6d56aaec240251338dc5704fda2227bdf88041bd90654fd99a71cc9823b11f431f3b0b5f136a5c19184c70c27c0606976df665c4c3de828f2d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
